import type { Metadata } from "next";
import { Manrope, Cardo, Kumbh_Sans } from "next/font/google";
import "./globals.css";

const kumbh_sans_init = Kumbh_Sans({
	subsets: ["latin"],
	weight: ["400", "700"],
	variable: "--font-kumbh",
});

export const metadata: Metadata = {
	title: "Leul Mesfin",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`${kumbh_sans_init.variable}`}>
				{children}
			</body> 
		</html>
	);
}
